version: '3.7'

networks:
  node-private-network:

volumes:
  node-data:

services:
  # add additional services here
  # add each service to the node-private-network for internal-only access
  # node accessible via http://node:4001 (AlgoD API) and http://node:4002 (KMD API)
  node:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - ALGORAND_NETWORK=${ALGORAND_NETWORK}
        - ALGORAND_DATA=${ALGORAND_DATA}
    # run as non-root user
    user: algorand:algorand
    restart: on-failure
    # ports:
      # no ports exposed to host
    networks:
      - node-private-network
    expose:
      # only exposes to other services through node-private-network
      - 4001 # AlgoD API
      - 4002 # KMD API
    environment:
      # injected from compose .env
      ALGORAND_DATA: ${ALGORAND_DATA}
      ALGORAND_NETWORK: ${ALGORAND_NETWORK}

    volumes:
      # persist in docker volume
      - node-data:/${ALGORAND_DATA}
